apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
        - name: binarycalculator
          image: us-central1-docker.pkg.dev/dynamic-parity-489312-c7/sofe3980u/binarycalculator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

